from flask import request, app, flash, redirect, url_for, render_template, abort, json
from flask_sqlalchemy import SQLAlchemy
from flaskr import db


class SoundData(db.Model,object):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, unique=False, nullable=False)
    file_uri = db.Column(db.String, unique=False, nullable=True)
    length = db.Column(db.Integer, unique=False, nullable=True)
    data = db.Column(db.DateTime, unique=False, nullable=True)

    #name field passed in, other fields generated by server
    def __init__(self, name = None, filename = None, length=None, date=None):
        self.name = name
        self.file_uri = filename
        self.length = length
        self.date = date

    def __repr__(self):
        return '<id: {}, name: {}, filename: {}>'.format(self.id, self.user, self.file_uri)

    def get_url(self):
        return url_for()

    #Called from Views(not needed with @marshal_with)
    def export_data(self):
        return {
            'name': self.name,
            'file_uri': self.file_uri,
            'length' : self.length,
            'date' : self.date
        }

    #Called from Views(not needed with @marshal_with)
    def import_metadata(self, request):
        try:
            json_data = request.get_json()
            if 'name' in json_data:
                self.user = json_data['name']
            if 'file_uri' in json_data:
                self.file_uri = json_data['file_uri']
            if 'length' in json_data:
                self.length = json_data['length']
            if 'date' in json_data:
                self.date = json_data['date']
        except KeyError as e:
            print "Key not found in metadata"

        #Import sound File
        self.import_file(request)
        return self


